# Generated by Django 5.1.4 on 2025-01-31 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=100)),
                ('diagnosis_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodDailyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_daily_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_name', models.CharField(max_length=100)),
                ('therapy_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=100)),
                ('med_quantity', models.CharField(max_length=100)),
                ('med_date', models.DateTimeField()),
                ('med_change', models.BooleanField(default=False)),
                ('med_observation', models.TextField()),
                ('referer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NurseCarerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_carer_record_date', models.DateTimeField()),
                ('nurse_carer_record_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateTimeField()),
                ('control_location', models.CharField(max_length=100)),
                ('control_observation', models.TextField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_date', models.DateTimeField()),
                ('medical_record_reason', models.CharField(max_length=100)),
                ('medical_record_actual_state', models.TextField()),
                ('medical_record_analysis', models.TextField()),
                ('medical_record_recommendation_plan', models.TextField()),
                ('medical_record_vital_signs', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_date', models.DateTimeField()),
                ('food_ingestion', models.CharField(blank=True, max_length=100, null=True)),
                ('food_eliminated', models.CharField(blank=True, max_length=100, null=True)),
                ('food_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_daily_date', models.DateTimeField()),
                ('food_daily_food', models.TextField()),
                ('food_daily_observation', models.TextField()),
                ('food_daily_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.fooddailytype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_control_name', models.CharField(max_length=100)),
                ('food_control_date', models.DateTimeField()),
                ('food_control_location', models.CharField(max_length=100)),
                ('food_control_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ArterialPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arterial_pressure', models.CharField(max_length=100)),
                ('arterial_pressure_date', models.DateTimeField()),
                ('heart_rate', models.CharField(max_length=100)),
                ('saturation', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField()),
                ('record_analysis', models.TextField(blank=True, null=True)),
                ('record_therapy', models.TextField(blank=True, null=True)),
                ('record_recommendation', models.TextField(blank=True, null=True)),
                ('record_observation', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emr.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
                ('therapy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emr.therapy')),
            ],
        ),
        migrations.CreateModel(
            name='WeightControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('weight_date', models.DateTimeField()),
                ('weight_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
    ]
