# Generated by Django 5.1.4 on 2025-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursecarerrecord',
            name='nurse_carer_record_type',
            field=models.CharField(blank=True, choices=[('Registro de enfermería', 'Registro de enfermería'), ('Registro de cuidador', 'Registro de cuidador')], max_length=30, null=True),
        ),
    ]
