# Generated by Django 5.1.4 on 2025-02-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_nursecarerrecord_nurse_carer_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='med_presentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TherapyMedicalValoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_medical_valoration_date', models.DateTimeField()),
                ('therapy_medical_valoration_reason', models.CharField(max_length=100)),
                ('therapy_medical_valoration_diagnostic', models.CharField(max_length=100)),
                ('therapy_medical_valoration_analysis', models.TextField()),
                ('therapy_medical_valoration_treatment_plan', models.TextField()),
                ('therapy_medical_valoration_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
    ]
