# Generated by Django 5.1.4 on 2025-01-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_arterialpressure_foodcontrol_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arterialpressure',
            name='arterial_pressure_time',
        ),
        migrations.RemoveField(
            model_name='foodcontrol',
            name='food_time',
        ),
        migrations.RemoveField(
            model_name='medicationcontrol',
            name='control_time',
        ),
        migrations.RemoveField(
            model_name='weightcontrol',
            name='weight_time',
        ),
        migrations.AlterField(
            model_name='arterialpressure',
            name='arterial_pressure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='foodcontrol',
            name='food_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='med_quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicationcontrol',
            name='control_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weightcontrol',
            name='weight_date',
            field=models.DateTimeField(),
        ),
    ]
