# Generated by Django 5.1.4 on 2025-02-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_medication_med_presentation_therapymedicalvaloration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapymedicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
