# Generated by Django 5.1.4 on 2025-01-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arterialpressure',
            name='arterial_pressure',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arterialpressure',
            name='heart_rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arterialpressure',
            name='saturation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arterialpressure',
            name='temperature',
            field=models.CharField(max_length=100),
        ),
    ]
