# Generated by Django 5.1.4 on 2025-01-27 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_alter_arterialpressure_arterial_pressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcontrol',
            old_name='food_date',
            new_name='food_control_date',
        ),
        migrations.RenameField(
            model_name='foodcontrol',
            old_name='food_location',
            new_name='food_control_location',
        ),
        migrations.RenameField(
            model_name='foodcontrol',
            old_name='food_name',
            new_name='food_control_name',
        ),
        migrations.RenameField(
            model_name='foodcontrol',
            old_name='food_observation',
            new_name='food_control_observation',
        ),
        migrations.CreateModel(
            name='FoodIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_date', models.DateTimeField()),
                ('food_ingestion', models.CharField(max_length=100)),
                ('food_eliminated', models.CharField(max_length=100)),
                ('food_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
            ],
        ),
    ]
