# Generated by Django 5.1.4 on 2025-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_rename_food_date_foodcontrol_food_control_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingestion',
            name='food_eliminated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodingestion',
            name='food_ingestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
