# Generated by Django 5.1.4 on 2025-01-29 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_alter_foodingestion_food_eliminated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=100)),
                ('diagnosis_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='record_description',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arterialpressure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='foodcontrol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='foodingestion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicationcontrol',
            name='med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.medication'),
        ),
        migrations.AlterField(
            model_name='medicationcontrol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AlterField(
            model_name='weightcontrol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emr.diagnosis'),
        ),
    ]
