# Generated by Django 5.1.4 on 2025-01-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_diagnosis_remove_medicalrecord_record_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_name', models.CharField(max_length=100)),
                ('therapy_description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='therapy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='emr.therapy'),
        ),
    ]
