# Generated by Django 5.1.4 on 2025-01-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0010_therapy_medicalrecord_therapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDailyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_daily_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_daily_date', models.DateTimeField()),
                ('food_daily_food', models.CharField(max_length=100)),
                ('food_daily_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
                ('food_daily_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.fooddailytype')),
            ],
        ),
    ]
