# Generated by Django 5.1.4 on 2025-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_fooddailytype_fooddaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddaily',
            name='food_daily_food',
            field=models.TextField(),
        ),
    ]
