# Generated by Django 5.1.4 on 2025-01-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0012_alter_fooddaily_food_daily_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseCarerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_carer_record_date', models.DateTimeField()),
                ('nurse_carer_record_observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emr.patient')),
            ],
        ),
    ]
